FROM golang:alpine
WORKDIR /oneterm
COPY . .
RUN go env -w GOPROXY=https://goproxy.cn,direct \
    && go build --ldflags "-s -w" -o ./build/oneterm ./main.go

FROM alpine:latest
RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk add tzdata
ENV TZ=Asia/Shanghai
ENV TERM=xterm-256color
WORKDIR /oneterm
COPY --from=0 /oneterm/config.example.yaml ./config.yaml
COPY --from=0 /oneterm/i18n/translate ./translate
COPY --from=0 /oneterm/build/oneterm .
CMD [ "./oneterm","run","-c","./config.yaml"]

