FROM golang:1.21.3-alpine3.17
WORKDIR /oneterm
COPY . .
RUN go env -w GOPROXY=https://goproxy.cn,direct \
    && go build --ldflags "-s -w" -o ./build/ssh ./cmd/ssh/ssh.go


FROM alpine:latest

RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    apk add tzdata && \
    apk add --update openssh && \
    mkdir -p '~/.ssh' && \
    echo "./ssh ssh -c config.yaml" > entrypoint.sh

ENV TZ=Asia/Shanghai
ENV TERM=xterm-color256
WORKDIR /oneterm

COPY  ./cmd/ssh/config.example.yaml config.yaml
COPY  ./pkg/i18n/translate ./translate
COPY --from=0 /oneterm/build/ssh .

ENTRYPOINT ["sh", "./entrypoint.sh"]

